# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44c0f626d0bff673ba3ccdc36ef5ff699981ac70ab5bb4af027d2c8298f3719dd42993c2b699552459945db900d615046dc5e40a25e3e1d995be452cfd5aacb6

test:
  secret_key_base: 58c30c0c3d16b088aaf9136fefb4d5548a74ca811fdc88152211dc6306b36c78b88fbe4362afeb82a6f4a2150b31e63b456c393a5fd3568093230773fd3dbbdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
